In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
if torch.cuda.is_available():
    print("cuda is available")
    print(torch.cuda.get_device_name(0))
else:
    print("cuda is not available. Using CPU")


cuda is available
Tesla T4


### Creating Tensor

In [4]:
# using empty
x = torch.empty(3,4)

In [5]:
# check type
type(x)

torch.Tensor

In [6]:
# using zeros
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
# using rand
torch.rand(3,4)

tensor([[0.8304, 0.6712, 0.4815, 0.9074],
        [0.6347, 0.7242, 0.4044, 0.6689],
        [0.1511, 0.2646, 0.8536, 0.3526]])

In [8]:
# use of seed
torch.manual_seed(42)
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [10]:
# for custom tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

### Tensor Shapes

In [11]:
a = torch.tensor([[1,2,3], [4,5,6]])

In [12]:
a.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(a)

tensor([[135379425610736, 135379459490032, 135379425610736],
        [135375528284672, 135375522853104, 135375528284816]])

In [14]:
torch.zeros_like(a)

tensor([[0, 0, 0],
        [0, 0, 0]])

### Tensor Datatypes

In [16]:
a.dtype

torch.int64

In [17]:
torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [21]:
# using to()
a.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operations

### 1. Scalar Operations

In [23]:
z = torch.rand(2,3)
z

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])

In [24]:
z + 2

tensor([[2.2666, 2.6274, 2.2696],
        [2.4414, 2.2969, 2.8317]])

### 2. Elementwise Operations

In [25]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [26]:
a + b

tensor([[1.0569, 0.3448, 1.2448],
        [0.7826, 0.8848, 0.8151]])

### 3. Reduction Operation

In [27]:
a = torch.randint(size=(2,3), low=0, high=10)
a

tensor([[9, 6, 2],
        [0, 6, 2]])

In [29]:
torch.sum(a)

# sum along cols
torch.sum(a, dim=0)

# sum along rows
torch.sum(a, dim=1)

tensor([17,  8])

### 4. Matrix Operations

In [30]:
a = torch.randint(size=(2,3), low=0, high=10)
b = torch.randint(size=(3,2), low=0, high=10)

In [31]:
torch.matmul(a,b)

tensor([[ 21, 193],
        [  9,  84]])

### 5. Comparison Operations

In [32]:
a = torch.randint(size=(2,3), low=0, high=10)
b = torch.randint(size=(2,3), low=0, high=10)

In [33]:
a > b

tensor([[False,  True,  True],
        [ True,  True,  True]])

### 6. Special Functions

In [34]:
i = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [35]:
torch.log(i)

tensor([[1.0986,   -inf, 0.0000],
        [0.0000, 1.9459, 2.1972]])

In [36]:
torch.exp(i)

tensor([[2.0086e+01, 1.0000e+00, 2.7183e+00],
        [2.7183e+00, 1.0966e+03, 8.1031e+03]])

In [37]:
torch.sqrt(i)

tensor([[1.7321, 0.0000, 1.0000],
        [1.0000, 2.6458, 3.0000]])

### 7. Inplace Operations

In [39]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [40]:
m + n

tensor([[1.6602, 1.0028, 0.2458],
        [0.2680, 0.9289, 1.0004]])

In [41]:
m.add_(n)

tensor([[1.6602, 1.0028, 0.2458],
        [0.2680, 0.9289, 1.0004]])

### Copying a tensor

In [44]:
a = torch.rand(3,4)
a

tensor([[0.9578, 0.3313, 0.3227, 0.0162],
        [0.2137, 0.6249, 0.4340, 0.1371],
        [0.5117, 0.1585, 0.0758, 0.2247]])

In [46]:
a[0][0] = 0

In [47]:
b = a.clone()
b

tensor([[0.0000, 0.3313, 0.3227, 0.0162],
        [0.2137, 0.6249, 0.4340, 0.1371],
        [0.5117, 0.1585, 0.0758, 0.2247]])

In [48]:
id(a)

135375502857680

In [49]:
id(b)

135375500845968

## Tensor Operations on GPU

In [50]:
torch.cuda.is_available()

True

In [51]:
device = torch.device('cuda')

In [53]:
# create a tensor on gpu
torch.rand((2,3), device=device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [54]:
# moving existing tensors to gpu
a = torch.rand((2,3))
a.to(device)

tensor([[0.1716, 0.3336, 0.5782],
        [0.0600, 0.2846, 0.2007]], device='cuda:0')

### Reshaping tensors

In [55]:
a = torch.ones(4,4)

In [57]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [58]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# permute

In [ ]:
# unsqueeze

In [ ]:
# squeeze

### Numpy and Pytorch

In [59]:
import numpy as np

In [60]:
a = torch.ones(3,4)

In [61]:
b = a.numpy()

In [62]:
type(b)

numpy.ndarray

In [63]:
c = np.array([[1,2,3],[4,5,6]])

In [64]:
torch.from_numpy(c)

tensor([[1, 2, 3],
        [4, 5, 6]])